cabal-version:      2.4
name:               directo
version:            0.1.0.0
synopsis:           directo - A Reflex FRP application
description:        A Reflex FRP application that can be built for web, Android, and iOS
license:            BSD-3-Clause
author:             hhefesto
maintainer:         hhefesto@rdataa.com
category:           Web
build-type:         Simple

executable dirClientFE
  main-is:          ClientFE.hs
  hs-source-dirs:   src

  build-depends:
      base
    , reflex
    , reflex-dom
    , reflex-dom-core
    , text
    , time
    , containers
    , rel8
    , aeson
    , hasql

  if !impl(ghcjs)
    build-depends:
        jsaddle
      , jsaddle-warp

  default-language: Haskell2010

  ghc-options:
    -Wall
    -fno-warn-unused-do-bind
    -threaded
    -rtsopts
    -with-rtsopts=-N

  if impl(ghcjs)
    ghc-options:
      -dedupe
    cpp-options:
      -DGHCJS_BROWSER

  default-extensions:
    OverloadedStrings
    RecursiveDo
    ScopedTypeVariables
    FlexibleContexts
    TypeFamilies
    ConstraintKinds

executable dirAdminFE
  main-is:          AdminFE.hs
  hs-source-dirs:   src

  build-depends:
      base
    , reflex
    , reflex-dom
    , reflex-dom-core
    , text
    , time
    , containers
    , rel8
    , aeson
    , hasql

  if !impl(ghcjs)
    build-depends:
        jsaddle
      , jsaddle-warp

  default-language: Haskell2010

  ghc-options:
    -Wall
    -fno-warn-unused-do-bind
    -threaded
    -rtsopts
    -with-rtsopts=-N

  if impl(ghcjs)
    ghc-options:
      -dedupe
    cpp-options:
      -DGHCJS_BROWSER

  default-extensions:
    OverloadedStrings
    RecursiveDo
    ScopedTypeVariables
    FlexibleContexts
    TypeFamilies
    ConstraintKinds

executable dirBackend
  main-is:          Backend.hs
  hs-source-dirs:   src

  build-depends:
      base
    , reflex
    , reflex-dom
    , reflex-dom-core
    , text
    , time
    , containers
    , rel8
    , aeson
    , hasql

  if !impl(ghcjs)
    build-depends:
        jsaddle
      , jsaddle-warp

  default-language: Haskell2010

  ghc-options:
    -Wall
    -fno-warn-unused-do-bind
    -threaded
    -rtsopts
    -with-rtsopts=-N

  if impl(ghcjs)
    ghc-options:
      -dedupe
    cpp-options:
      -DGHCJS_BROWSER

  default-extensions:
    OverloadedStrings
    RecursiveDo
    ScopedTypeVariables
    FlexibleContexts
    TypeFamilies
    ConstraintKinds
